### ISSUE TITLE
Update the tower to be compatible with new versions of Google Android

### ISSUE THREAD

**Issue by Korb** [TrueWatcher/tower#6] opened 2024-07-12 11:56 UTC
[F-Droid](https://f-droid.org/en/packages/truewatcher.tower/):

> This app was built for an older version of Android and cannot be updated automatically.

> OS version: Funtouch OS 14
> Model: Vivo T1 4G (V2153)
> Hardware version: MP_0.1
> Build number: PD22010F_EX_A_14.2.7.12.W20
> Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.88
> Kernel version: 4.19.157-perf+, 1 Wed Jun 5 10:25:33 CST 2024
> Compile time: 5 Jun 2024 05:20:41
> Android security update: 1 June 2024
> Google Play system update: 1 May 2024

**Comment by TrueWatcher** [comment] 2024-07-14 19:59
Thanks for the report.

The latest version 2.9.6 has targetSdkVersion=30.  That is enough for Android 14, that has [Minimum installable target API level](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level) = 23.

Does your Funtouch OS 14 have higher requirements than its base Android 14 ?

**Comment by Korb** [comment] 2024-07-15 06:54
> The latest version 2.9.6 has targetSdkVersion=30. That is enough for Android 14, that has [Minimum installable target API level](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level) = 23.

I confirm that currently the latest available (suggested) version in F-Droid is 2.9.6 (75) added on 12/20/2023.

> Size: 1.7 MiB
> Android: 5.0+

> Does your Funtouch OS 14 have higher requirements than its base Android 14?

Unfortunately, I can't tell you this, I don't know. I can only say that some applications in F-Droid have the mark indicated in the first post, and some do not.

**Comment by TrueWatcher** [comment] 2024-07-15 19:35
> some applications in F-Droid have the mark indicated in the first post

Do you mean by "mark"

> This app was built for an older version of Android and cannot be updated automatically.

?

I don't see that phrase on the F-droid app [page](https://f-droid.org/en/packages/truewatcher.tower/).
It looks like an error message, but what program gave you that  and in what situation? Can I reproduce it?

`

**Comment by Korb** [comment] 2024-07-16 06:18
![Screenshot_2024_0716_091616_org fdroid fdroid](https://github.com/user-attachments/assets/4777c35a-c107-492d-9c20-99db4db39c5a)

> The latest version 2.9.6 has targetSdkVersion=**30**. That is enough for Android 14, that has [Minimum installable target API level](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level) = **23**.

> Android 14: targetSdk will need to be **34+** for new apps and app updates by August 31, 2024.
https://apilevels.com/

Can you try to make a version with the API Level 34 (June 2023) or API Level 35 (June 2024)?

**Comment by TrueWatcher** [comment] 2024-07-16 18:24
> It looks like an error message, but what program gave you that and in what situation? Can I reproduce it?

Thanks to your screenshot, I can now answer my own questions. It's a note by the F-droid client app. To reproduce it, I had to install the F-droid client on a Android 14 and search for Tower. I've never used it before, as I have a habit of installing APKs directly. That way or this, the Tower is installable and workable in an Android 14 emulator.

> Android 14: targetSdk will need to be 34+ for new apps and app updates by August 31, 2024. https://apilevels.com/

This refers to [GooglePlay's requirement](https://developer.android.com/google/play/requirements/target-sdk) , which is relevant to Google's customer policy, not to actual Android OS behavior ([Minimum installable target API level](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level) 23).  I personally don't use Google Play and have no intention to put any apps there.

> Can you try to make a version with the API Level 34 (June 2023) or API Level 35 (June 2024)?

I can tell you, even without trying, that simply rebuilding the app with higher target API level will result in it no longer working, or just crashing on first run. Because that level determines how the code must interact with system APIs, and these requirements are changing. For example, since 31 an app cannot request the FINE_LOCATION permission without requesting COARSE_LOCATION permission (that for a navigator app is really weird) .

I'll probably upgrade the app to API 33 or 34 sometimes later, but now I'm about to close this issue.

**Closed as not planned** 2024-07-17 04:26 UTC
